projects:
  producercollab:
    schemaPath: Users/risvitareq/code/producer-collab/client/src/graphql/schema.json
    includes:
      - server/schemas/typeDefs.mjs
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: server/schemas
extensions:
  amplify:
    version: 3
