service: producer-collab-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: server/app.handler # Specify the handler for your Lambda function
    events:
      - httpApi: '*' # Add HTTP events for your API endpoints
