service: serverless-express-apollo

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGODB_URI: mongodb+srv://ivsir:Ulang1411!@producer-collab.dyoeqvd.mongodb.net/?retryWrites=true&w=majority&appName=producer-collab
    MY_AWS_PROFILE: ivsir-general
    MY_AWS_REGION: us-west-1
    BUCKET: react-image-upload-ivsir

functions:
  app:
    handler: server/server.handler
    events:
      - http:
          path: create-s3-folder
          method: post
      - http:
          path: user-folders
          method: get
      - http:
          path: images
          method: post
      - http:
          path: audiofiles
          method: post
      - http:
          path: upload
          method: post
      - http:
          path: images
          method: get
      - http:
          path: audiofiles
          method: get
      - http:
          path: singlepost-image
          method: get
      - http:
          path: files
          method: get
      - http:
          path: graphql
          method: any

plugins:
  - serverless-offline
  # - serverless-dotenv-plugin
  - serverless-prune-plugin

custom:
  serverless-offline:
    httpPort: 4001
  # dotenv:
  #   path: ./server/.env
  prune:
    automatic: true
    number: 3

package:
  exclude:
    - client/** 
    - package-lock.json
    - node_modules/**
  excludeDevDependencies: true
