service: serverless-express-apollo

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGODB_URI: mongodb+srv://ivsir:Ulang1411!@producer-collab.dyoeqvd.mongodb.net/?retryWrites=true&w=majority&appName=producer-collab
    MY_AWS_PROFILE: ivsir-general
    MY_AWS_REGION: us-west-1
    BUCKET: react-image-upload-ivsir

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::react-image-upload-ivsir/*"
        - "arn:aws:s3:::react-image-upload-ivsir"
    - Effect: Allow
      Action:
        - sts:AssumeRole
      Resource: "arn:aws:iam::614288690243:user/ivsir"

functions:
  app:
    handler: server/server.graphqlHandler
    events:
      - http:
          path: graphql
          method: any
          cors: true
      - http:
          path: playground
          method: ANY
          cors: true
  rest:
    handler: server/server.restHandler
    events:
      - http:
          path: create-s3-folder
          method: post
          cors: true
      - http:
          path: user-folders
          method: get
          cors: true
      - http:
          path: images
          method: post
          cors: true
      - http:
          path: audiofiles
          method: post
          cors: true
      - http:
          path: upload
          method: post
          cors: true
      - http:
          path: images
          method: get
          cors: true
      - http:
          path: audiofiles
          method: get
          cors: true
      - http:
          path: files
          method: get
          cors: true
      - http:
          path: singlepost-image
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-prune-plugin

custom:
  serverless-offline:
    httpPort: 4001
  prune:
    automatic: true
    number: 3

package:
  exclude:
    - client/** 
    - package-lock.json
    - node_modules/**
  excludeDevDependencies: true
