version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - run:
          name: Deploy app to Heroku
          command: |
            git push https://heroku:$34501918-dcdd-4f67-9596-74727dc7b5c9@git.heroku.com/$gentle-headland-15406.git main

workflows:
  build-deploy:
    jobs:
      - deploy